// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXmuR4wv14VNS0Ktb7Yw6LQV_lrFXpUFg',
    appId: '1:57253512363:web:c45b59a6fbe1c136eb23ee',
    messagingSenderId: '57253512363',
    projectId: 'chat-app-bebe7',
    authDomain: 'chat-app-bebe7.firebaseapp.com',
    storageBucket: 'chat-app-bebe7.appspot.com',
    measurementId: 'G-S1YGBH8GX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uYegna4_mLb29EDG_-bkPv6sOxBY4AA',
    appId: '1:57253512363:android:8acdfa90ce727d7ceb23ee',
    messagingSenderId: '57253512363',
    projectId: 'chat-app-bebe7',
    storageBucket: 'chat-app-bebe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCerbu-Du6fLT9835PwjTmUQFAHaKE8MMc',
    appId: '1:57253512363:ios:e5c05e1da500ffd0eb23ee',
    messagingSenderId: '57253512363',
    projectId: 'chat-app-bebe7',
    storageBucket: 'chat-app-bebe7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCerbu-Du6fLT9835PwjTmUQFAHaKE8MMc',
    appId: '1:57253512363:ios:e5c05e1da500ffd0eb23ee',
    messagingSenderId: '57253512363',
    projectId: 'chat-app-bebe7',
    storageBucket: 'chat-app-bebe7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXmuR4wv14VNS0Ktb7Yw6LQV_lrFXpUFg',
    appId: '1:57253512363:web:362ba1a572313057eb23ee',
    messagingSenderId: '57253512363',
    projectId: 'chat-app-bebe7',
    authDomain: 'chat-app-bebe7.firebaseapp.com',
    storageBucket: 'chat-app-bebe7.appspot.com',
    measurementId: 'G-J3QS11ZT5S',
  );
}
